// SPDX-License-Identifier: GPL-3.0-or-later
//! Writes the table of country names the catalogue's place keys use (design note 008 §5.1).
//!
//! `cargo run -p auroraw-places --example country-names -- <ne_10m_admin_0_countries.geojson> <output file>`
//!
//! One line per country: its ISO 3166-1 alpha-2 code, its alpha-3 code, then the names it goes by, separated by tabs.
//! The names are the ones Natural Earth gives (its short, long, formal, English and French names, and the name it
//! "breaks" by) and a short list of the names people still write (`aliases` below), so that a photo whose tool gave
//! `Canada` and no code is the same country as one that gave `Canada` and `CA`. The catalogue folds the names when it
//! loads the table; it does not need them folded here.
//!
//! The table is committed (`crates/catalogue/src/country_names.tsv`) and regenerated by hand when the data is: it is a
//! small, reviewed file, not something every build derives from a download. Natural Earth is in the public domain.

use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use serde_json::Value;

/// Names people write for a country that Natural Earth's names do not include: `(code, name)`. Each code must be one
/// of the data's (the tool stops otherwise), so a typo cannot add a country.
const ALIASES: &[(&str, &str)] = &[
    ("GB", "UK"),
    ("GB", "U.K."),
    ("GB", "Great Britain"),
    ("GB", "Britain"),
    ("US", "U.S."),
    ("US", "U.S.A."),
    ("US", "United States of America"),
    ("US", "America"),
    ("MM", "Burma"),
    ("CI", "Ivory Coast"),
    ("SZ", "Swaziland"),
    ("MK", "Macedonia"),
    ("CV", "Cape Verde"),
    ("TL", "East Timor"),
    ("TR", "Türkiye"),
    ("TR", "Turkiye"),
    ("NL", "Holland"),
    ("NL", "The Netherlands"),
    ("CZ", "Czech Republic"),
    ("KR", "Republic of Korea"),
    ("KP", "Democratic People's Republic of Korea"),
    ("VA", "Vatican City"),
    ("VA", "Holy See"),
    ("RU", "Russian Federation"),
];

/// The properties of a country that hold a name.
const NAME_PROPERTIES: &[&str] = &[
    "NAME",
    "NAME_LONG",
    "ADMIN",
    "FORMAL_EN",
    "NAME_EN",
    "BRK_NAME",
    "NAME_FR",
];

fn text(properties: &Value, key: &str) -> Option<String> {
    let value = properties.get(key)?.as_str()?.trim();
    (!value.is_empty() && value != "-99").then(|| value.to_string())
}

fn main() {
    let mut arguments = std::env::args().skip(1);
    let (Some(input), Some(output)) = (arguments.next(), arguments.next()) else {
        eprintln!("usage: country-names <ne_10m_admin_0_countries.geojson> <output file>");
        std::process::exit(2);
    };
    let (input, output) = (PathBuf::from(input), PathBuf::from(output));
    let document: Value = serde_json::from_str(
        &std::fs::read_to_string(&input)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", input.display())),
    )
    .expect("GeoJSON");
    let features = document
        .get("features")
        .and_then(Value::as_array)
        .expect("a list of features");

    // code -> (alpha-3, names). A feature with no ISO code (Somaliland, Northern Cyprus) is not a country a
    // photo's code can name, and is left out; its names would only be taken from a country that has one.
    let mut countries: BTreeMap<String, (String, BTreeSet<String>)> = BTreeMap::new();
    for feature in features {
        let Some(properties) = feature.get("properties") else {
            continue;
        };
        // `ISO_A2` is "-99" for France and Norway (overseas territories): the `_EH` code fixes them.
        let Some(code) = text(properties, "ISO_A2_EH").or_else(|| text(properties, "ISO_A2"))
        else {
            continue;
        };
        let alpha3 = text(properties, "ISO_A3_EH")
            .or_else(|| text(properties, "ISO_A3"))
            .unwrap_or_default();
        let entry = countries
            .entry(code)
            .or_insert_with(|| (alpha3, BTreeSet::new()));
        for key in NAME_PROPERTIES {
            if let Some(name) = text(properties, key) {
                entry.1.insert(name);
            }
        }
    }
    for (code, name) in ALIASES {
        match countries.get_mut(*code) {
            Some(entry) => {
                entry.1.insert((*name).to_string());
            }
            None => {
                eprintln!("the alias {name:?} names {code}, which is not in the data");
                std::process::exit(1);
            }
        }
    }

    // A name two countries share is no name for either: the catalogue drops it when it loads the table, and this
    // tool says which, so that a change of the data that makes one is seen.
    let mut owners: BTreeMap<String, BTreeSet<&str>> = BTreeMap::new();
    for (code, (_, names)) in &countries {
        for name in names {
            owners
                .entry(name.to_lowercase())
                .or_default()
                .insert(code.as_str());
        }
    }
    for (name, codes) in owners.iter().filter(|(_, codes)| codes.len() > 1) {
        eprintln!("the name {name:?} is shared by {codes:?}");
    }

    let mut out = String::new();
    out.push_str("# The countries and the names they go by, for the place keys of the catalogue (design note 008 §5.1).\n");
    out.push_str("# Made by `cargo run -p auroraw-places --example country-names` from Natural Earth 5.1.2\n");
    out.push_str("# (ne_10m_admin_0_countries, public domain) and the aliases of that example. Do not edit by hand.\n");
    out.push_str("# Columns, separated by tabs: ISO 3166-1 alpha-2, alpha-3, then the names.\n");
    for (code, (alpha3, names)) in &countries {
        out.push_str(code);
        out.push('\t');
        out.push_str(alpha3);
        for name in names {
            out.push('\t');
            out.push_str(name);
        }
        out.push('\n');
    }
    std::fs::write(&output, out)
        .unwrap_or_else(|e| panic!("cannot write {}: {e}", output.display()));
    println!(
        "{}: {} countries, {} names",
        output.display(),
        countries.len(),
        countries.values().map(|(_, n)| n.len()).sum::<usize>()
    );
}
