// SPDX-License-Identifier: GPL-3.0-or-later
pragma Singleton
import QtQuick

// The icons of the interface (D-137): a font of their own, `assets/fonts/AurorawIcons.ttf`, in which each icon is a
// character of the Unicode private-use area, so that an icon is set like text: its colour is `color`, its size the
// `font.pixelSize`, and it is as sharp as text on every platform and every rendering backend.
//
// GENERATED by `tools/icons/build_icons.py`, from the outlines defined there: change an icon or add one there, and
// run it; do not edit this file. `AppIcon.qml` is the item to draw one with.
QtObject {
    property FontLoader loader: FontLoader { source: Qt.resolvedUrl("../assets/fonts/AurorawIcons.ttf") }
    readonly property string family: loader.name
    readonly property var codes: ({
        "star": "\ue000",
        "star-outline": "\ue001",
        "check": "\ue002",
        "close": "\ue003",
        "caret-down": "\ue004",
        "caret-up": "\ue005",
        "caret-left": "\ue006",
        "caret-right": "\ue007",
        "menu": "\ue008",
        "chevrons-right": "\ue009",
        "chevrons-left": "\ue00a",
        "minus": "\ue00b",
        "series": "\ue00c"
    })
    readonly property var names: Object.keys(codes)

    // The character of icon `name`, or nothing for a name that is not one.
    function glyph(name) {
        return codes[name] || ""
    }

    // The Unicode characters the interface used before it had icons, and the icon that replaces each.
    readonly property var legacy: ({
        "\u2605": "star",
        "\u2606": "star-outline",
        "\u2714": "check",
        "\u2713": "check",
        "\u2716": "close",
        "\u2715": "close",
        "\u25be": "caret-down",
        "\u25bc": "caret-down",
        "\u25b2": "caret-up",
        "\u25b8": "caret-right",
        "\u25b6": "caret-right",
        "\u25c0": "caret-left",
        "\u2630": "menu",
        "\u25a3": "series"
    })

    // `text` cut into runs, for `AppIconLabel`: a run of the icons that replace those characters, `{ text: "<their
    // characters>", icons: true }`, or a run of what lies between them, `{ text: "...", icons: false }`. A sentence
    // that comes from elsewhere (the summary the engine writes under the grid) can hold them, and the icons are set in
    // the icon font, the rest in the text's own.
    function runs(text) {
        const out = []
        let run = { text: "", icons: false }
        for (const ch of String(text)) {
            const icons = legacy[ch] !== undefined
            if (icons !== run.icons && run.text !== "") {
                out.push(run)
                run = { text: "", icons: icons }
            }
            run.icons = icons
            run.text += icons ? glyph(legacy[ch]) : ch
        }
        if (run.text !== "")
            out.push(run)
        return out
    }
}
